
spring:
  datasource:
    url: jdbc:mysql://10.168.4.13:3306/content_tag?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
    username: root
    password: xRHM#BD%P4hY
    driver-class-name: com.mysql.cj.jdbc.Driver