
#spring:
#  datasource:
#    单数据源的jdbc配置前缀为url
#    url: jdbc:mysql://127.0.0.1:3306/qingyun?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    qingyun:
      #多数据源的jdbc配置前缀为 jdbc-url
      jdbc-url: jdbc:mysql://127.0.0.1:3306/qingyun?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

    qingwan:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/qingwan?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver